name: Daily Stock Screener to Google Sheets

on:
  schedule:
    - cron: '30 10 * * *'  # Every day at 8:00 UTC
  workflow_dispatch:  # Also allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > creds.json
          python screener.py
